from pathlib import Path
path = Path('LEGISLACAO_md_to_csv_converter.py')
text = path.read_text(encoding='utf-8')
old_block = "                candidate = candidate.replace('_', '')\n                candidate = candidate.replace('.�', '�').replace('.�', '�')\n                candidate = re.sub(r'(\\d+)\\s*[oO]\\b', r'\\1�', candidate)\n                candidate = re.sub(r'�\\s+', '�', candidate)\n                candidate = re.sub(r'\\s*\\(\\s*', ' (', candidate)\n                candidate = re.sub(r'\\s+\\)', ')', candidate)\n                candidate = re.sub(r'\\)\\s*(?=\\()', ') (', candidate)\n                candidate = re.sub(r'^ \\(', '(', candidate)\n                candidate = re.sub(r'\\(\\s*\\(', '(', candidate)\n                candidate = re.sub(r'\\)\\s*\\)', ')', candidate)\n                candidate = re.sub(r'\\[\\s*\\]\\([^)]+\\)', '', candidate)  # remove empty markdown links\n                candidate = re.sub(r'\\(\\s*https?://[^)]+\\)', '', candidate)  # remove bare url references\n                candidate = re.sub(r'https?://\\S+', '', candidate)  # remove any remaining bare urls\n\n                candidate = re.sub(r'[ \\t]+', ' ', candidate)\n                candidate = candidate.rstrip(',[]* ')\n                candidate = collapse_duplicate_text(candidate)\n"
new_block = "                candidate = candidate.replace('_', '')\n                candidate = candidate.replace('.º', 'º').replace('.ª', 'ª')\n                candidate = re.sub(r'(\\d+)\\s*[oO]\\b', r'\\1º', candidate)\n                candidate = re.sub(r'§\\s+', '§', candidate)\n                candidate = re.sub(r'(?i)(Lei)\\s+n\\s*o\\b', r'\\1 nº', candidate)\n                candidate = re.sub(r'\\s*\\(\\s*', ' (', candidate)\n                candidate = re.sub(r'\\s+\\)', ')', candidate)\n                candidate = re.sub(r'\\)\\s*(?=\\()', ') (', candidate)\n                candidate = re.sub(r'^ \\(', '(', candidate)\n                candidate = re.sub(r'\\(\\s*\\(', '(', candidate)\n                candidate = re.sub(r'\\)\\s*\\)', ')', candidate)\n                candidate = re.sub(r'\\[\\s*\\]\\([^)]+\\)', '', candidate)\n                candidate = re.sub(r'\\(\\s*https?://[^)]+\\)', '', candidate)\n                candidate = re.sub(r'https?://\\S+', '', candidate)\n\n                candidate = re.sub(r'[ \\t]+', ' ', candidate)\n                candidate = candidate.rstrip(',[]* ')\n                candidate = collapse_duplicate_text(candidate)\n"
if old_block not in text:
    raise SystemExit('old block not found (candidate)')
text = text.replace(old_block, new_block, 1)
path.write_text(text, encoding='utf-8')
